# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DetectionService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44\x65tectionService.proto\x12\x04yolo\"H\n\x17YoloDetectionUrlRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12 \n\x06params\x18\x02 \x01(\x0b\x32\x10.yolo.YoloParams\"G\n\x14YoloDetectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12 \n\x06params\x18\x02 \x01(\x0b\x32\x10.yolo.YoloParams\"e\n\x15YoloDetectionResponse\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.yolo.YoloDetectionResult\x12 \n\x06params\x18\x02 \x01(\x0b\x32\x10.yolo.YoloParams\";\n\nYoloParams\x12\x16\n\x0e\x63onf_threshold\x18\x01 \x01(\x02\x12\x15\n\riou_threshold\x18\x02 \x01(\x02\"h\n\x13YoloDetectionResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\n\n\x02x1\x18\x03 \x01(\x03\x12\n\n\x02y1\x18\x04 \x01(\x03\x12\n\n\x02x2\x18\x05 \x01(\x03\x12\n\n\x02y2\x18\x06 \x01(\x03\x32\xf5\x01\n\x14YoloDetectionService\x12M\n\x0c\x44\x65tectStream\x12\x1a.yolo.YoloDetectionRequest\x1a\x1b.yolo.YoloDetectionResponse\"\x00(\x01\x30\x01\x12\x43\n\x06\x44\x65tect\x12\x1a.yolo.YoloDetectionRequest\x1a\x1b.yolo.YoloDetectionResponse\"\x00\x12I\n\tDetectUrl\x12\x1d.yolo.YoloDetectionUrlRequest\x1a\x1b.yolo.YoloDetectionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DetectionService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _YOLODETECTIONURLREQUEST._serialized_start=32
  _YOLODETECTIONURLREQUEST._serialized_end=104
  _YOLODETECTIONREQUEST._serialized_start=106
  _YOLODETECTIONREQUEST._serialized_end=177
  _YOLODETECTIONRESPONSE._serialized_start=179
  _YOLODETECTIONRESPONSE._serialized_end=280
  _YOLOPARAMS._serialized_start=282
  _YOLOPARAMS._serialized_end=341
  _YOLODETECTIONRESULT._serialized_start=343
  _YOLODETECTIONRESULT._serialized_end=447
  _YOLODETECTIONSERVICE._serialized_start=450
  _YOLODETECTIONSERVICE._serialized_end=695
# @@protoc_insertion_point(module_scope)
